[2016-04-19 22:59:18,052] [ERROR] base : Internal Server Error: /
Traceback (most recent call last):
  File "c:\anaconda2\lib\site-packages\django-1.8.7-py2.7.egg\django\core\handlers\base.py", line 164, in get_response
    response = response.render()
  File "c:\anaconda2\lib\site-packages\django-1.8.7-py2.7.egg\django\template\response.py", line 158, in render
    self.content = self.rendered_content
  File "c:\anaconda2\lib\site-packages\django-1.8.7-py2.7.egg\django\template\response.py", line 135, in rendered_content
    content = template.render(context, self._request)
  File "c:\anaconda2\lib\site-packages\django-1.8.7-py2.7.egg\django\template\backends\django.py", line 74, in render
    return self.template.render(context)
  File "c:\anaconda2\lib\site-packages\django-1.8.7-py2.7.egg\django\template\base.py", line 210, in render
    return self._render(context)
  File "c:\anaconda2\lib\site-packages\django-1.8.7-py2.7.egg\django\template\base.py", line 202, in _render
    return self.nodelist.render(context)
  File "c:\anaconda2\lib\site-packages\django-1.8.7-py2.7.egg\django\template\base.py", line 905, in render
    bit = self.render_node(node, context)
  File "c:\anaconda2\lib\site-packages\django-1.8.7-py2.7.egg\django\template\debug.py", line 79, in render_node
    return node.render(context)
  File "c:\anaconda2\lib\site-packages\django-1.8.7-py2.7.egg\django\template\loader_tags.py", line 135, in render
    return compiled_parent._render(context)
  File "c:\anaconda2\lib\site-packages\django-1.8.7-py2.7.egg\django\template\base.py", line 202, in _render
    return self.nodelist.render(context)
  File "c:\anaconda2\lib\site-packages\django-1.8.7-py2.7.egg\django\template\base.py", line 905, in render
    bit = self.render_node(node, context)
  File "c:\anaconda2\lib\site-packages\django-1.8.7-py2.7.egg\django\template\debug.py", line 79, in render_node
    return node.render(context)
  File "c:\anaconda2\lib\site-packages\django-1.8.7-py2.7.egg\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "c:\anaconda2\lib\site-packages\django-1.8.7-py2.7.egg\django\template\base.py", line 905, in render
    bit = self.render_node(node, context)
  File "c:\anaconda2\lib\site-packages\django-1.8.7-py2.7.egg\django\template\debug.py", line 79, in render_node
    return node.render(context)
  File "c:\anaconda2\lib\site-packages\django-1.8.7-py2.7.egg\django\template\loader_tags.py", line 159, in render
    return template.render(context)
  File "c:\anaconda2\lib\site-packages\django-1.8.7-py2.7.egg\django\template\base.py", line 212, in render
    return self._render(context)
  File "c:\anaconda2\lib\site-packages\django-1.8.7-py2.7.egg\django\template\base.py", line 202, in _render
    return self.nodelist.render(context)
  File "c:\anaconda2\lib\site-packages\django-1.8.7-py2.7.egg\django\template\base.py", line 905, in render
    bit = self.render_node(node, context)
  File "c:\anaconda2\lib\site-packages\django-1.8.7-py2.7.egg\django\template\debug.py", line 79, in render_node
    return node.render(context)
  File "c:\anaconda2\lib\site-packages\django-1.8.7-py2.7.egg\django\template\defaulttags.py", line 217, in render
    nodelist.append(node.render(context))
  File "c:\anaconda2\lib\site-packages\django-1.8.7-py2.7.egg\django\template\defaulttags.py", line 507, in render
    six.reraise(*exc_info)
  File "c:\anaconda2\lib\site-packages\django-1.8.7-py2.7.egg\django\template\defaulttags.py", line 493, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "c:\anaconda2\lib\site-packages\django-1.8.7-py2.7.egg\django\core\urlresolvers.py", line 578, in reverse
    return force_text(iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs)))
  File "c:\anaconda2\lib\site-packages\django-1.8.7-py2.7.egg\django\core\urlresolvers.py", line 495, in _reverse_with_prefix
    (lookup_view_s, args, kwargs, len(patterns), patterns))
NoReverseMatch: Reverse for 'article-detail-view' with arguments '(u'Mysql conf under ubuntu',)' and keyword arguments '{}' not found. 1 pattern(s) tried: ['article/(?P<slug>\\w+).html$']
[2016-04-19 22:59:18,052] [ERROR] base : Internal Server Error: /
Traceback (most recent call last):
  File "c:\anaconda2\lib\site-packages\django-1.8.7-py2.7.egg\django\core\handlers\base.py", line 164, in get_response
    response = response.render()
  File "c:\anaconda2\lib\site-packages\django-1.8.7-py2.7.egg\django\template\response.py", line 158, in render
    self.content = self.rendered_content
  File "c:\anaconda2\lib\site-packages\django-1.8.7-py2.7.egg\django\template\response.py", line 135, in rendered_content
    content = template.render(context, self._request)
  File "c:\anaconda2\lib\site-packages\django-1.8.7-py2.7.egg\django\template\backends\django.py", line 74, in render
    return self.template.render(context)
  File "c:\anaconda2\lib\site-packages\django-1.8.7-py2.7.egg\django\template\base.py", line 210, in render
    return self._render(context)
  File "c:\anaconda2\lib\site-packages\django-1.8.7-py2.7.egg\django\template\base.py", line 202, in _render
    return self.nodelist.render(context)
  File "c:\anaconda2\lib\site-packages\django-1.8.7-py2.7.egg\django\template\base.py", line 905, in render
    bit = self.render_node(node, context)
  File "c:\anaconda2\lib\site-packages\django-1.8.7-py2.7.egg\django\template\debug.py", line 79, in render_node
    return node.render(context)
  File "c:\anaconda2\lib\site-packages\django-1.8.7-py2.7.egg\django\template\loader_tags.py", line 135, in render
    return compiled_parent._render(context)
  File "c:\anaconda2\lib\site-packages\django-1.8.7-py2.7.egg\django\template\base.py", line 202, in _render
    return self.nodelist.render(context)
  File "c:\anaconda2\lib\site-packages\django-1.8.7-py2.7.egg\django\template\base.py", line 905, in render
    bit = self.render_node(node, context)
  File "c:\anaconda2\lib\site-packages\django-1.8.7-py2.7.egg\django\template\debug.py", line 79, in render_node
    return node.render(context)
  File "c:\anaconda2\lib\site-packages\django-1.8.7-py2.7.egg\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "c:\anaconda2\lib\site-packages\django-1.8.7-py2.7.egg\django\template\base.py", line 905, in render
    bit = self.render_node(node, context)
  File "c:\anaconda2\lib\site-packages\django-1.8.7-py2.7.egg\django\template\debug.py", line 79, in render_node
    return node.render(context)
  File "c:\anaconda2\lib\site-packages\django-1.8.7-py2.7.egg\django\template\loader_tags.py", line 159, in render
    return template.render(context)
  File "c:\anaconda2\lib\site-packages\django-1.8.7-py2.7.egg\django\template\base.py", line 212, in render
    return self._render(context)
  File "c:\anaconda2\lib\site-packages\django-1.8.7-py2.7.egg\django\template\base.py", line 202, in _render
    return self.nodelist.render(context)
  File "c:\anaconda2\lib\site-packages\django-1.8.7-py2.7.egg\django\template\base.py", line 905, in render
    bit = self.render_node(node, context)
  File "c:\anaconda2\lib\site-packages\django-1.8.7-py2.7.egg\django\template\debug.py", line 79, in render_node
    return node.render(context)
  File "c:\anaconda2\lib\site-packages\django-1.8.7-py2.7.egg\django\template\defaulttags.py", line 217, in render
    nodelist.append(node.render(context))
  File "c:\anaconda2\lib\site-packages\django-1.8.7-py2.7.egg\django\template\defaulttags.py", line 507, in render
    six.reraise(*exc_info)
  File "c:\anaconda2\lib\site-packages\django-1.8.7-py2.7.egg\django\template\defaulttags.py", line 493, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "c:\anaconda2\lib\site-packages\django-1.8.7-py2.7.egg\django\core\urlresolvers.py", line 578, in reverse
    return force_text(iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs)))
  File "c:\anaconda2\lib\site-packages\django-1.8.7-py2.7.egg\django\core\urlresolvers.py", line 495, in _reverse_with_prefix
    (lookup_view_s, args, kwargs, len(patterns), patterns))
NoReverseMatch: Reverse for 'article-detail-view' with arguments '(u'Mysql conf under ubuntu',)' and keyword arguments '{}' not found. 1 pattern(s) tried: ['article/(?P<slug>\\w+).html$']
[2016-04-19 23:04:04,257] [ERROR] base : Internal Server Error: /
Traceback (most recent call last):
  File "c:\anaconda2\lib\site-packages\django-1.8.7-py2.7.egg\django\core\handlers\base.py", line 164, in get_response
    response = response.render()
  File "c:\anaconda2\lib\site-packages\django-1.8.7-py2.7.egg\django\template\response.py", line 158, in render
    self.content = self.rendered_content
  File "c:\anaconda2\lib\site-packages\django-1.8.7-py2.7.egg\django\template\response.py", line 135, in rendered_content
    content = template.render(context, self._request)
  File "c:\anaconda2\lib\site-packages\django-1.8.7-py2.7.egg\django\template\backends\django.py", line 74, in render
    return self.template.render(context)
  File "c:\anaconda2\lib\site-packages\django-1.8.7-py2.7.egg\django\template\base.py", line 210, in render
    return self._render(context)
  File "c:\anaconda2\lib\site-packages\django-1.8.7-py2.7.egg\django\template\base.py", line 202, in _render
    return self.nodelist.render(context)
  File "c:\anaconda2\lib\site-packages\django-1.8.7-py2.7.egg\django\template\base.py", line 905, in render
    bit = self.render_node(node, context)
  File "c:\anaconda2\lib\site-packages\django-1.8.7-py2.7.egg\django\template\debug.py", line 79, in render_node
    return node.render(context)
  File "c:\anaconda2\lib\site-packages\django-1.8.7-py2.7.egg\django\template\loader_tags.py", line 135, in render
    return compiled_parent._render(context)
  File "c:\anaconda2\lib\site-packages\django-1.8.7-py2.7.egg\django\template\base.py", line 202, in _render
    return self.nodelist.render(context)
  File "c:\anaconda2\lib\site-packages\django-1.8.7-py2.7.egg\django\template\base.py", line 905, in render
    bit = self.render_node(node, context)
  File "c:\anaconda2\lib\site-packages\django-1.8.7-py2.7.egg\django\template\debug.py", line 79, in render_node
    return node.render(context)
  File "c:\anaconda2\lib\site-packages\django-1.8.7-py2.7.egg\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "c:\anaconda2\lib\site-packages\django-1.8.7-py2.7.egg\django\template\base.py", line 905, in render
    bit = self.render_node(node, context)
  File "c:\anaconda2\lib\site-packages\django-1.8.7-py2.7.egg\django\template\debug.py", line 79, in render_node
    return node.render(context)
  File "c:\anaconda2\lib\site-packages\django-1.8.7-py2.7.egg\django\template\loader_tags.py", line 159, in render
    return template.render(context)
  File "c:\anaconda2\lib\site-packages\django-1.8.7-py2.7.egg\django\template\base.py", line 212, in render
    return self._render(context)
  File "c:\anaconda2\lib\site-packages\django-1.8.7-py2.7.egg\django\template\base.py", line 202, in _render
    return self.nodelist.render(context)
  File "c:\anaconda2\lib\site-packages\django-1.8.7-py2.7.egg\django\template\base.py", line 905, in render
    bit = self.render_node(node, context)
  File "c:\anaconda2\lib\site-packages\django-1.8.7-py2.7.egg\django\template\debug.py", line 79, in render_node
    return node.render(context)
  File "c:\anaconda2\lib\site-packages\django-1.8.7-py2.7.egg\django\template\defaulttags.py", line 217, in render
    nodelist.append(node.render(context))
  File "c:\anaconda2\lib\site-packages\django-1.8.7-py2.7.egg\django\template\defaulttags.py", line 507, in render
    six.reraise(*exc_info)
  File "c:\anaconda2\lib\site-packages\django-1.8.7-py2.7.egg\django\template\defaulttags.py", line 493, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "c:\anaconda2\lib\site-packages\django-1.8.7-py2.7.egg\django\core\urlresolvers.py", line 578, in reverse
    return force_text(iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs)))
  File "c:\anaconda2\lib\site-packages\django-1.8.7-py2.7.egg\django\core\urlresolvers.py", line 495, in _reverse_with_prefix
    (lookup_view_s, args, kwargs, len(patterns), patterns))
NoReverseMatch: Reverse for 'article-detail-view' with arguments '(u'Mysql ',)' and keyword arguments '{}' not found. 1 pattern(s) tried: ['article/(?P<slug>\\w+).html$']
[2016-04-19 23:04:04,257] [ERROR] base : Internal Server Error: /
Traceback (most recent call last):
  File "c:\anaconda2\lib\site-packages\django-1.8.7-py2.7.egg\django\core\handlers\base.py", line 164, in get_response
    response = response.render()
  File "c:\anaconda2\lib\site-packages\django-1.8.7-py2.7.egg\django\template\response.py", line 158, in render
    self.content = self.rendered_content
  File "c:\anaconda2\lib\site-packages\django-1.8.7-py2.7.egg\django\template\response.py", line 135, in rendered_content
    content = template.render(context, self._request)
  File "c:\anaconda2\lib\site-packages\django-1.8.7-py2.7.egg\django\template\backends\django.py", line 74, in render
    return self.template.render(context)
  File "c:\anaconda2\lib\site-packages\django-1.8.7-py2.7.egg\django\template\base.py", line 210, in render
    return self._render(context)
  File "c:\anaconda2\lib\site-packages\django-1.8.7-py2.7.egg\django\template\base.py", line 202, in _render
    return self.nodelist.render(context)
  File "c:\anaconda2\lib\site-packages\django-1.8.7-py2.7.egg\django\template\base.py", line 905, in render
    bit = self.render_node(node, context)
  File "c:\anaconda2\lib\site-packages\django-1.8.7-py2.7.egg\django\template\debug.py", line 79, in render_node
    return node.render(context)
  File "c:\anaconda2\lib\site-packages\django-1.8.7-py2.7.egg\django\template\loader_tags.py", line 135, in render
    return compiled_parent._render(context)
  File "c:\anaconda2\lib\site-packages\django-1.8.7-py2.7.egg\django\template\base.py", line 202, in _render
    return self.nodelist.render(context)
  File "c:\anaconda2\lib\site-packages\django-1.8.7-py2.7.egg\django\template\base.py", line 905, in render
    bit = self.render_node(node, context)
  File "c:\anaconda2\lib\site-packages\django-1.8.7-py2.7.egg\django\template\debug.py", line 79, in render_node
    return node.render(context)
  File "c:\anaconda2\lib\site-packages\django-1.8.7-py2.7.egg\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "c:\anaconda2\lib\site-packages\django-1.8.7-py2.7.egg\django\template\base.py", line 905, in render
    bit = self.render_node(node, context)
  File "c:\anaconda2\lib\site-packages\django-1.8.7-py2.7.egg\django\template\debug.py", line 79, in render_node
    return node.render(context)
  File "c:\anaconda2\lib\site-packages\django-1.8.7-py2.7.egg\django\template\loader_tags.py", line 159, in render
    return template.render(context)
  File "c:\anaconda2\lib\site-packages\django-1.8.7-py2.7.egg\django\template\base.py", line 212, in render
    return self._render(context)
  File "c:\anaconda2\lib\site-packages\django-1.8.7-py2.7.egg\django\template\base.py", line 202, in _render
    return self.nodelist.render(context)
  File "c:\anaconda2\lib\site-packages\django-1.8.7-py2.7.egg\django\template\base.py", line 905, in render
    bit = self.render_node(node, context)
  File "c:\anaconda2\lib\site-packages\django-1.8.7-py2.7.egg\django\template\debug.py", line 79, in render_node
    return node.render(context)
  File "c:\anaconda2\lib\site-packages\django-1.8.7-py2.7.egg\django\template\defaulttags.py", line 217, in render
    nodelist.append(node.render(context))
  File "c:\anaconda2\lib\site-packages\django-1.8.7-py2.7.egg\django\template\defaulttags.py", line 507, in render
    six.reraise(*exc_info)
  File "c:\anaconda2\lib\site-packages\django-1.8.7-py2.7.egg\django\template\defaulttags.py", line 493, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "c:\anaconda2\lib\site-packages\django-1.8.7-py2.7.egg\django\core\urlresolvers.py", line 578, in reverse
    return force_text(iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs)))
  File "c:\anaconda2\lib\site-packages\django-1.8.7-py2.7.egg\django\core\urlresolvers.py", line 495, in _reverse_with_prefix
    (lookup_view_s, args, kwargs, len(patterns), patterns))
NoReverseMatch: Reverse for 'article-detail-view' with arguments '(u'Mysql ',)' and keyword arguments '{}' not found. 1 pattern(s) tried: ['article/(?P<slug>\\w+).html$']
[2016-04-20 09:32:53,059] [ERROR] views : [UserControl]用户上传头像为空:[%s]
[2016-04-20 10:07:31,414] [ERROR] views : [CommentControl]当前用户非活动用户:[]
